#! /bin/sh

#---Autostart---#
pgrep -x sxhkd > /dev/null || sxhkd &
/usr/bin/dunst &
~/.config/polybar/launch.sh &
picom &
nitrogen --restore &

#---Monitors---#
bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 10 &
bspc monitor DP-0 -d 11 12 13 14 15 16 17 18 19 20 &

#---Global Settings---#
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

bspc config focus_follows_pointer   true
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc focus_by_distance              true
bspc history_aware_focus            true
bspc config pointer_motion_interval 7

bspc config normal_border_color     "#363a4f"
bspc config active_border_color     "#e5e9f0"
bspc config focused_border_color    "#5e81ac"
bspc config presel_feedback_color   "#b7bdf8"

#---Window Settings---#
bspc config top_padding             0
bspc config bottom_padding          40
bspc config border_width            4
bspc config window_gap              25

bspc config split_ratio             0.50

#---Rules---#
bspc rule -a '*:*:Picture-in-Picture' state=floating sticky=on
bspc rule -a '*:*:Picture-in-picture' state=floating sticky=on
bspc rule -a Zathura state=tiled
bspc rule -a Clockify state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Protonvpn state=floating
bspc rule -a mpv state=floating
bspc rule -a Gpick state=floating
bspc rule -a Pavucontrol state=floating
